# Generated by Django 3.2.9 on 2021-12-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=15)),
                ('lName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Counsel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=15)),
                ('lName', models.CharField(max_length=15)),
                ('firmN', models.CharField(max_length=100)),
                ('phoneN', models.IntegerField()),
                ('Address', models.CharField(max_length=15)),
                ('Address2', models.CharField(max_length=15)),
                ('zip_code', models.IntegerField()),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ViewCounsel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
